language: go
go:
- '1.7'
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- make deps
script:
- make test
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
    secure: UTDabFFeO9vycSGw4bJZ+kz6DK3ujkx1GHdyi09QO2XRNtsJWpSP+gwEOKsqgLvGP/ePyJ0cg81yBBIVoAiXA7cEV84R/e473N/WbyTLlBDOTJingi4aJeDh077j/t0SZ8iFyXWAnhB2dSZzotjs/9OlnStoYZnTO6c4Zc1pnGmCnWPcXZKvJFBTJpteXMlo2BupydeFLNcVQW9tlW5jvy5HeNqncqLfQ0AZa1XEk/KDTFLguA+EPqMk5eoDyZhgb0hyfAEirTRKtzpb9OQptlZ+qbBHHX7nLDo8kUommyigAzeAXsvNCrPRGScsULKt++G56KKukPpa1gVdXfKMV5yxko02FaNPS59TmAzLWTOCdZwVcPvZvqfQABaDYI3uLj37jaOeE68ubYp/TysdJKDBEeDo7sCDo8Kj1gUfhPfP/MbgYTDns7KZpGcelUZpBSn7yTWJ45NU2LpPfV9EZQjiUQ6Xa20Pn7nF3FW4yT0uVHKsMwU4BjHZJI32K1ZyU2kK5d+DHASL4u9JxC/FCOpp4gwqtO7oJGfEdupGAxMUaS3fJZ+J4c3aLvchtIj9gs2MDbXviJKTaHcVfMrKoRQXwPUO+tAF8KHFaBJPSybIfQv4AezXyJ6x6pMzjz11bFooT+wj2oUIarxfH9QjfSl5o+dde/UdKmpb3u5ZGis=
